# Generated by Django 2.0 on 2020-03-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ratecompany', '0002_auto_20200303_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(),
        ),
    ]
