# Generated by Django 2.1.5 on 2020-03-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ratecompany', '0004_auto_20200323_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='score',
            field=models.IntegerField(verbose_name='mark'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='avatar/default.jpg', max_length=1000, upload_to='avatar', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=11, null=True, verbose_name='telephone number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=0, verbose_name='gender'),
        ),
    ]
