# Generated by Django 2.1.5 on 2020-03-25 15:41

import Ratecompany.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ratecompany', '0005_auto_20200323_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='atmosphere',
            field=Ratecompany.models.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='salary',
            field=Ratecompany.models.IntegerRangeField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='wellfare',
            field=Ratecompany.models.IntegerRangeField(),
        ),
    ]
