# Generated by Django 2.1.5 on 2020-03-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ratecompany', '0008_company_emailtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='emailtag',
            field=models.CharField(max_length=128),
        ),
    ]
